DefaultContentLanguage = "en"
baseurl = "/"
canonifyurls = true
disqusShortname = "www-coastsystems-net"
metaDataFormat = "toml"
paginate = 10
paginatePath = "page"
theme = "hugo-bootstrap-premium"
[Languages.en]
copyright = "(c) 2018 Boyd Kelly"
languageCode = "en"
languageName = "English"
title = "Coast Business Technologies"
weight = 1
[[Languages.en.menu.main]]
identifier = "post"
name = "Blog"
pre = ""
url = "/post/"
weight = 6
[[Languages.en.menu.main]]
identifier = "about"
name = "About"
pre = "<i class='fa fa-road'></i>"
url = "/about"
weight = 1
[[Languages.en.menu.main]]
identifier = "tech"
name = "Technology"
url = "/topics/Technology"
weight = 2
[[Languages.en.menu.main]]
identifier = "aef"
name = "English in French"
url = "/topics/English in French"
weight = 3
[[Languages.en.menu.main]]
identifier = "jula"
name = "Julakan"
url = "/topics/Julakan"
weight = 4
[[Languages.en.menu.switchlang]]
identifier = "fr"
name = "Français"
url = "fr"
weight = 7
[Languages.fr]
copyright = "(c) 2018 Boyd Kelly"
languageCode = "fr"
languageName = "Français"
title = "Coast Business Technologies"
weight = 2
[[Languages.fr.menu.main]]
identifier = "post"
name = "Blog"
pre = ""
url = "/post/"
weight = 6
[[Languages.fr.menu.main]]
identifier = ""
name = "À propos"
pre = "<i class='fa fa-road'></i>"
url = "/about"
weight = 1
[[Languages.fr.menu.main]]
identifier = "tech"
name = "Technologie"
url = "/topics/Technologie"
weight = 2
[[Languages.fr.menu.main]]
identifier = "aef"
name = "Anglais en français"
url = "/topics/Anglais en français"
weight = 3
[[Languages.fr.menu.main]]
identifier = "jula"
name = "Julakan"
url = "/topics/Julakan"
weight = 4
[[Languages.fr.menu.switchlang]]
identifier = "en"
name = "English"
url = "en"
weight = 7
[Languages.fr.taxonomies]
tag = "tags"
topic = "topics"
[author]
email = "bkelly@coastsystems.net"
name = "Boyd Kelly"
[blackfriday]
angledQuotes = true
extensionmask = []
extensions = []
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
[params]
BrandImage = ""
bitbucket = ""
bootswatchtheme = "paper"
brand = "Coast Business Technologies"
customCSS = ["/css/style_custom.css"]
customJS = []
facebook = "Myprofile"
flattr = ""
github = "www.githubmcom/boydkelly"
googleAnalytics = "UA-7938441-2"
googleplus = "Myprofile"
highlight = "default"
home = "about"
linkedin = "www.linkedin.com/in/boydkelly"
mailmunchid = ""
mathjax = ""
showRightSidebar = true
sumomeid = ""
switchlang = true
topline = "Technology, Language, Accounting"
twitter = "www.twitter.com/boydkelly"
youtube = ""
[permalinks]
code = "/:filename/"
post = "/:year/:month/:day/:filename/"
[taxonomies]
tag = "tags"
topic = "topics"
