---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Posts
- type: directory
  path: content/post
  label: English
  create: documents
  match: "**/*.md"
  exclude: "**/*.fr.md"
  templates:
  - post
- type: directory
  path: content/post
  label: French
  create: documents
  match: "**/*.fr.md"
  new_doc_ext: fr.md
  templates:
  - french
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/post
  label: All Posts
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.68.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.44'
